---
# tasks file for first_play
- name: Create a target directory
  ansible.builtin.file:
    path: "{{jhome}}"
    state: directory
    mode: '0755'

- name: Copy the Java file to target directory
  ansible.builtin.copy:
    src: "/tmp/{{package}}"
    dest: "{{jhome}}/{{package}}"
    mode: '0755'

- name: Install java package
  ansible.builtin.dnf:
    name: "{{jhome}}/{{package}}"
    state: present

- name: Install and update the java alternatives
  ansible.builtin.shell: |
    alternatives --install /usr/bin/java {{java_path}} {{java_priority}}
    update-alternatives --set java {{java_path}}
  register: java_alter_result

- name: Update profile file
  ansible.builtin.blockinfile:
    path: "{{profile_file}}"
    block: |
      export JAVA_HOME={{jhome}}
      export PATH=$PATH:$JAVA_HOME/java-x86_64-80/bin
    state: present
  when: java_alter_result.rc == 0

- name: Source of profile file
  ansible.builtin.shell: |
    source {{profile_file}}
    java -version
  register: java_output

- name: java version output
  debug:
    var: java_output.stdout_lines
